x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  app:
    build:
      context: dev/docker
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-false}
    ports:
      - "${API_PORT}:80"     # set your app port here
      - "40000:40000" # set your debug port here
    working_dir: /app
    volumes:
      - "./:/app"
      - ".env:/app/.env:ro"
      - "go_mod_cache:/go/pkg/mod"
      - "go_build_cache_app:/go/cache"
    command:
      - "cmd/http/main.go"
    restart: unless-stopped
    logging: *default-logging

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # RabbitMQ management UI
      - "5672:5672"   # RabbitMQ default port
    volumes:
      - "./dev/rabbitmq-plugins:/etc/rabbitmq/enabled_plugins"

  redis:
    image: redis:7.2-rc-alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "16379:8001"

volumes:
  go_mod_cache:
    name: "${APP_NAME}_go_mod_cache"

  go_build_cache_app:
    name: "${APP_NAME}_go_build_cache_app"
